//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoliceSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Criminal
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string FName { get; set; }
        public string Photo { get; set; }
        public string Cnic { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string Crime { get; set; }
        public string Discription { get; set; }
        public string Charges { get; set; }
    }
}
